// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyyCwm_TQ4hdu5CnYEmlTMvl2x3AqGjo',
    appId: '1:903529616247:web:8ca2b5bb495f0e8a054772',
    messagingSenderId: '903529616247',
    projectId: 'debt-39eb8',
    authDomain: 'debt-39eb8.firebaseapp.com',
    storageBucket: 'debt-39eb8.firebasestorage.app',
    measurementId: 'G-WRG81Y9GMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaDJk9b6otRgbAJsyds5acU9KKdUZnEx4',
    appId: '1:903529616247:android:114ffd5854113f36054772',
    messagingSenderId: '903529616247',
    projectId: 'debt-39eb8',
    storageBucket: 'debt-39eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFelJ67MADuySB4NX_Dga2lvhC8vuNIA',
    appId: '1:903529616247:ios:15c98270129f9993054772',
    messagingSenderId: '903529616247',
    projectId: 'debt-39eb8',
    storageBucket: 'debt-39eb8.firebasestorage.app',
    iosBundleId: 'com.example.tahaDebts',
  );

}